### ISSUE TITLE
Pytorch Lightning sample doesn't work with distributed training

### ISSUE THREAD

**Issue by Data-drone** [wandb/gitbook#21]
When I run a distributed training job with the dpp backend, the pytorch example doesn't work?

I get an issue with:

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 389, in ddp_train
    self.run_pretrain_routine(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in run_pretrain_routine
    self.configure_checkpoint_callback()
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_config.py", line 58, in configure_checkpoint_callback
    "checkpoints"
  File "/opt/conda/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/conda/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

I added in the wand_logger as per the instructions:

```
    trainer = pl.Trainer(
        max_epochs=hparams.epochs,
        gpus=hparams.gpus,
        distributed_backend=hparams.distributed_backend,
        precision=16 if hparams.use_16bit else 32,
        logger=wandb_logger
    )


```

as per the docu

**Comment by cvphelps** [comment]
Hi @Data-drone could you please use our [main issue tracker](https://github.com/wandb/client) for issues with the client? We updated the PyTorch Lightning integration for the latest version, which should fix this issue you were seeing.
